networks:
  inception:
    driver: bridge

services:
  nginx:
    env_file: .env
    build: ./requirements/nginx
    container_name: nginx
    restart: on-failure
    ports:
      - "443:443"
    volumes:
      - ./data/wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: on-failure
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    env_file: .env
    volumes:
      - ./data/wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: on-failure
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    env_file: .env
    volumes:
      - ./data/mariadb:/var/lib/mysql
    networks:
      - inception